FROM freqtradeorg/freqtrade:2025.10

# Switch to root user
USER root

RUN apt-get update && apt-get install -y git

# Switch to ftuser user
USER ftuser

RUN pip3 install ta tqdm scipy plotly yfinance
